apiVersion: apps/v1
kind: Deployment
metadata:
  name: cicd-deployment
  labels:
    app: cicd
spec:
  replicas: 3
  selector:
    matchLabels:
      app: cicd
  template:
    metadata:
      labels:
        app: cicd
    spec:
      terminationGracePeriodSeconds: 30  # ✅ Moved outside of containers
      containers:
      - name: cicd-container
        image: amjad123ali/django:${IMAGE_TAG}  # ✅ Dynamically set IMAGE_TAG
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: cicd-service
spec:
  type: LoadBalancer
  selector:
    app: cicd
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
