name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

    - name: Set Image Tag
      run: echo "IMAGE_TAG=$(echo $GITHUB_SHA | cut -c1-7)" >> $GITHUB_ENV

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag amjad123ali/django:$IMAGE_TAG

    - name: Push the Docker image
      run: docker push amjad123ali/django:$IMAGE_TAG

  deployk8:  # This job is now correctly placed under 'jobs'
    needs: build  # Ensures deployment runs after the build job
    runs-on: ubuntu-latest  # Use latest Ubuntu runner

    steps:
    - uses: actions/checkout@v4  # Checkout the repository code

    - name: Run Deployment Script
      run: ./deploy.sh  # Executes the deploy script
